### ISSUE TITLE
Cannot override temporal config files using environmental variables.

### ISSUE THREAD

**Issue by brotich** [canonical/temporal-worker-k8s-operator#36]
According to https://charmhub.io/temporal-worker-k8s/configurations#environment, the environmental variables are read in order of vault -> juju -> environmental variables.

However, this means that config options in the charm i.e `TEMPORAL_ENCRYPTION_KEY` cannot be overridden using the higher priority variable storage. i.e the following config will not respect the `TEMPORAL_ENCRYPTION_KEY` from the juju secret, rather it will be reset to an empty `TEMPORAL_ENCRYPTION_KEY`

```yaml
juju:
    - secret-id: {secret_id}
      name: TEMPORAL_ENCRYPTION_KEY
      key: encryption-key
vault:
    - path: secrets
      name: access_token
      key: token
```
